
import { useEffect, useRef } from "react";
import { cn } from "@/lib/utils";
import { CheckCircle } from "lucide-react";

const About = () => {
  const sectionRef = useRef<HTMLElement>(null);
  
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            entry.target.classList.add('animate-fade-up');
            entry.target.classList.remove('opacity-0');
            entry.target.classList.add('opacity-100');
          }
        });
      },
      { threshold: 0.1 }
    );
    
    const elements = sectionRef.current?.querySelectorAll('.animate-on-scroll');
    elements?.forEach(el => observer.observe(el));
    
    return () => {
      elements?.forEach(el => observer.unobserve(el));
    };
  }, []);

  const features = [
    {
      title: "Accurate Tracking",
      description: "Our advanced algorithms calculate your carbon footprint based on your lifestyle choices and consumption patterns."
    },
    {
      title: "Personalized Solutions",
      description: "Receive customized recommendations that fit your lifestyle to help reduce your carbon footprint effectively."
    },
    {
      title: "Track Progress",
      description: "Monitor your improvements over time and see the positive impact your changes are making on the environment."
    },
    {
      title: "Save Money",
      description: "Many carbon-reducing actions also lead to financial savings through reduced energy and resource consumption."
    }
  ];

  return (
    <section 
      id="about" 
      ref={sectionRef}
      className="py-20 bg-carbon-light/30"
    >
      <div className="section-container">
        <div className="text-center mb-12 animate-on-scroll opacity-0 transition-all duration-700">
          <h2 className="text-3xl md:text-4xl font-display font-bold mb-4 tracking-tight">
            Understanding Your <span className="text-gradient">Carbon Footprint</span>
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto text-balance">
            Your carbon footprint is the total amount of greenhouse gases generated by your actions. 
            Knowing your impact is the first step toward a more sustainable future.
          </p>
        </div>
        
        <div className="grid md:grid-cols-2 gap-12 items-center">
          <div className="order-2 md:order-1">
            <div className="space-y-6">
              {features.map((feature, index) => (
                <div 
                  key={index}
                  className="animate-on-scroll opacity-0 transition-all duration-700"
                  style={{ transitionDelay: `${index * 100}ms` }}
                >
                  <div className="flex items-start space-x-4">
                    <div className="mt-1 flex-shrink-0 rounded-full bg-carbon-light p-1">
                      <CheckCircle className="h-5 w-5 text-carbon-primary" />
                    </div>
                    <div>
                      <h3 className="font-semibold text-lg">{feature.title}</h3>
                      <p className="text-muted-foreground">{feature.description}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
          
          <div className="order-1 md:order-2 animate-on-scroll opacity-0 transition-all duration-700">
            <div className="relative">
              <div className="absolute -inset-1 rounded-xl bg-gradient-to-r from-carbon-primary to-carbon-dark blur-sm opacity-20"></div>
              <div className="relative rounded-xl overflow-hidden glassmorphism p-1">
                <img 
                  src="https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&q=80&w=2000"
                  alt="Nature landscape with sunlight"
                  className="rounded-lg w-full h-auto object-cover aspect-[4/3]"
                  loading="lazy"
                />
              </div>
              <div className="absolute -z-10 right-5 bottom-5 w-24 h-24 bg-carbon-accent/20 rounded-full blur-xl"></div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default About;
